### PR TITLE
new designs for component dropdown

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Summary

figma: https://www.figma.com/design/ln2VDACenFEkjVeHkowxyi/iR-Engine-Design-Library-File?node-id=2975-8101&node-type=frame&t=SwEFyU3IX1KemUBX-0

## References

closes https://tsu.atlassian.net/browse/IR-4942

## QA Steps

image

### CODE REVIEW

**Review by CITIZENDOT — CHANGES_REQUESTED** [review]
image
this icon is missing. I think this component should be a draggable component, so that it can be rearranged in the menu.

**Comment by aditya-mitra** [comment]
> image this icon is missing. I think this component should be a draggable component, so that it can be rearranged in the menu.

yes. drag and drop for the dropdown needs to be implemented in the component panel as a whole. we can do this once the main design goes in as a lot of things are dependent on implementing it. i will create a separate ticket

**Review by CITIZENDOT — APPROVED** [review]

**Review by CITIZENDOT — APPROVED** [review]
Nicely done!

**Comment by aditya-mitra** [comment]
> Nicely done!

regex is powerful 💪🏻

**Pull request merged**
