### PR TITLE
Fix annoying mui error

### PR DESCRIPTION
**Pull request by CITIZENDOT**
## Summary
- Often we encounter the error: createTheme_default is not a function. This PR fixes it.
- Redesigns OAuth callback pages (responsive design).
- Refactor all Oauth callback pages into one single component
- Remove unused MUI code.

## References
closes #_insert number here_

## QA Steps
image

### CODE REVIEW

**Review by hanzlamateen — APPROVED** [review]
Looks good to me. Though will have to wait for @HexaField

**Comment by HexaField** [comment]
I don't think we need this. We should instead focus on removing MUI

**Comment by HexaField** [comment]
see slack discussion

**Review by HexaField — APPROVED** [review]

**Comment by CITIZENDOT** [comment]
I'm removing some unused MUI components, I'll merge this PR after those changes.

**Review by HexaField — APPROVED** [review]

**Pull request merged**
