### PR TITLE
various fixes for spectate mode

### PR DESCRIPTION
**Pull request by HexaField**
## References
closes #_insert number here_

### CODE REVIEW

**Comment by DanielBelmes** [comment]
Just commenting things we did on discord.

- Spectate Button always on widget bar
- Spectate didn't seem to start and just gives user

**Comment by HexaField** [comment]
> Just commenting things we did on discord.
> 
> * Spectate Button always on widget bar
> * Spectate didn't seem to start and just gives user

fixed. very temperamental reactor.

**Review by AidanCaruso — APPROVED** [review]
Definitely an improvement, however forcing scene spectate with and without an entity from scene settings still doesn't seem to work properly. Enabling scene spectate from settings without an optional target entity doesn't serialize anymore.

**Comment by HexaField** [comment]
> Definitely an improvement, however forcing scene spectate with and without an entity from scene settings still doesn't seem to work properly. Enabling scene spectate from settings without an optional target entity doesn't serialize anymore.

We're going to be refactoring this property soon, so I'm not worried about it just yet.

**Pull request merged**
