### PR TITLE
IR-5822: update avatar selection & avatar creator menus

### PR DESCRIPTION
**Pull request by jose-galvan**
## Summary

- Removed buttons in footer. Now changes are saved when modal is dismissed
- Added back arrow that redirects to profile (only in /location) 
- Updated labels
- Redirect back to avatar list after RPM avatar is exported

image

image

image

## References
closes #_insert number here_

### CODE REVIEW

**Review by kattsushi — APPROVED** [review]
LGTM

**Comment by DanielBelmes** [comment]
image
I'm seeing this when running locally

**Comment by AidanCaruso** [comment]
@DanielBelmes I've fixed this scaling issue in my [PR](https://github.com/ir-engine/ir-engine/pull/786). It's also on dev.

**Comment by DanielBelmes** [comment]
Smoke test is looking great

**Pull request merged**
