### PR TITLE
IR-4556: Added group id to Mailchimp settings

### PR DESCRIPTION
**Pull request by jose-galvan**
## Summary

This PR introduces a new `groupId` field to the Mailchimp settings. The `groupId` will enable automatic assignment of users who sign up to a specific Mailchimp group, improving subscriber segmentation. With this update, campaign targeting becomes more precise, allowing for more personalized and relevant communication to distinct subscriber groups.

https://mailchimp.com/help/getting-started-with-groups/
image

## References
closes #_insert number here_

## QA Steps

1.- Run the migrations command
2.- Go to the admin panel 
3.- Look for the Mailchimp section in Settings
4.- Set new group id and save the changes

### CODE REVIEW

**Review by hanzlamateen — CHANGES_REQUESTED** [review]
Since this change is MT specific. We should introduce this group Id thing to mailchimp settings through MT project. Like we did for metabase in https://github.com/theinfinitereality/irpro-multitenancy/blob/fd6c0ec2d4ff3ffbd416ad725d4882fe2257fc67/services/integrations/metabase/metabase-setting

**Comment by jose-galvan** [comment]
> Since this change is MT specific. We should introduce this group Id thing to mailchimp settings through MT project. Like we did for metabase in https://github.com/theinfinitereality/irpro-multitenancy/blob/fd6c0ec2d4ff3ffbd416ad725d4882fe2257fc67/services/integrations/metabase/metabase-setting

I don't see how Mailchimp groups is specific to MT when it's just a standard functionality provided by Mailchimp. 
groups help you categorize users based on their interests. One example would be how often they want to receive 
a newsletter they subscribed to; Weekly, Monthly, etc.. 
If anything the complete integration should be moved into MT but that would generate issues to get appConfig updated

**Comment by hanzlamateen** [comment]
> > Since this change is MT specific. We should introduce this group Id thing to mailchimp settings through MT project. Like we did for metabase in https://github.com/theinfinitereality/irpro-multitenancy/blob/fd6c0ec2d4ff3ffbd416ad725d4882fe2257fc67/services/integrations/metabase/metabase-setting
> 
> I don't see how Mailchimp groups is specific to MT when it's just a standard functionality provided by Mailchimp. groups help you categorize users based on their interests. One example would be how often they want to receive a newsletter they subscribed to; Weekly, Monthly, etc.. If anything the complete integration should be moved into MT but that would generate issues to get appConfig updated

I dont see the group id being used anywhere in core engine. Its just being used in MT. 

@HexaField your thoughts on this?

**Comment by HexaField** [comment]
> I dont see the group id being used anywhere in core engine. Its just being used in MT. 
> 
> @HexaField your thoughts on this?

Yeah we can keep group id in MT

**Comment by jose-galvan** [comment]
> > > Since this change is MT specific. We should introduce this group Id thing to mailchimp settings through MT project. Like we did for metabase in https://github.com/theinfinitereality/irpro-multitenancy/blob/fd6c0ec2d4ff3ffbd416ad725d4882fe2257fc67/services/integrations/metabase/metabase-setting
> > 
> > 
> > I don't see how Mailchimp groups is specific to MT when it's just a standard functionality provided by Mailchimp. groups help you categorize users based on their interests. One example would be how often they want to receive a newsletter they subscribed to; Weekly, Monthly, etc.. If anything the complete integration should be moved into MT but that would generate issues to get appConfig updated
> 
> I dont see the group id being used anywhere in core engine. Its just being used in MT.
> 
> @HexaField your thoughts on this?

Neither is any of the other settings being used in core engine, server, list id, audience id are all used only in MT 
the only reason they live in core engine it's cause that's where the settings are managed. 
I'd recommend you read the Mailchimp documentation to understand how it works and how thing are being used.

**Comment by HexaField** [comment]
Fair enough. This is fine then.

**Review by hanzlamateen — APPROVED** [review]
@mshafiqmk we will need to move mailchimp-setting into MT project. Once we migrate this service into engine-setting. https://tsu.atlassian.net/browse/IR-3457

**Pull request merged**
