### PR TITLE
[IR-6048] add dragging and dropping functionality to the debug menu

### PR DESCRIPTION
**Pull request by kattsushi**
## Summary
Ir 6048 add dragging and dropping functionality to the debug menu

https://github.com/user-attachments/assets/4b03e65f-82be-4592-ae8a-44573a7f4aef

## References
related tikcet [#IR-6048](https://tsu.atlassian.net/browse/IR-6048)

### CODE REVIEW

**Comment by DanielBelmes** [comment]
https://github.com/user-attachments/assets/96378c8f-0e22-496d-b949-82ff30315680

**Review by DanielBelmes — CHANGES_REQUESTED** [review]
While smoke testing there were a lot of times when dragging the debugger it would get stuck to the mouse and you could only get it unhooked by moving mouse out of browser.

**Comment by kattsushi** [comment]
> While smoke testing there were a lot of times when dragging the debugger it would get stuck to the mouse and you could only get it unhooked by moving mouse out of browser.

thanks! let me check it out

**Comment by HexaField** [comment]
Screenshot from 2024-12-12 12-06-37
The grabber should not scroll with the rest of the panel. if I scroll down with lots of content, i can't drag it around.

**Comment by kattsushi** [comment]
> Screenshot from 2024-12-12 12-06-37 The grabber should not scroll with the rest of the panel. if I scroll down with lots of content, i can't drag it around.

thank you very much for the feedback i just already fix this case here the example


https://github.com/user-attachments/assets/aa61a308-8607-4cc0-b4c7-0859096ec050

**Review by DanielBelmes — APPROVED** [review]

**Pull request merged**
