### PR TITLE
Ir 4294 create prefab fix

### PR DESCRIPTION
**Pull request by JT00y**
## References
https://tsu.atlassian.net/browse/IR-4294

### CODE REVIEW

**Review by AidanCaruso — APPROVED** [review]
looks good, this fixes the extra assets directory. 

as a note, this change is predicated on exportRelativeGLTF now concatenating the importFolder. if we're keeping that, it would also make sense to remove the editable 'assets/' start to the prefab path input field text.
image

**Review by dinomut1 — APPROVED** [review]

**Comment by dinomut1** [comment]
Still seeing the issue with the cache not getting reset when a prefab is overwritten. That is out of scope for this ticket but we should resolve that soon

**Comment by dinomut1** [comment]
https://tsu.atlassian.net/browse/IR-4294

**Comment by dinomut1** [comment]
closing this as reverting gltf export fixes this

**Pull request closed without merging**
