### PR TITLE
[IR-5684] ] warning message on location for mobile devices

### PR DESCRIPTION
**Pull request by achen5671**
## Summary
https://tsu.atlassian.net/browse/IR-5684
## References
closes #_insert number here_

### CODE REVIEW

**Comment by barankyle** [comment]
I wasn't involved with picking the wording of this message, so maybe it's exactly as intended, but should there be an additional sentence or sentence fragment like "for best experience use desktop Chrome"? Or changing it from saying "mobile not supported" to "not optimized for mobile, experience might have issues"? To me, there's a disconnect between the modal saying mobile isn't supported and then, on mobile Chrome, at least, the scene loading and then appearing to be fine (granted, I just tested this on the default and sky-station scenes, so heavier/more complex scenes it might be more obvious).

**Review by DanielBelmes — APPROVED** [review]

**Comment by DanielBelmes** [comment]
Sorry it's late and I remembered to review your PR's. I approve but do agree with kyle's statement if it fits visually.

**Review by HexaField — APPROVED** [review]

**Comment by HexaField** [comment]
This may be unnecessary at all, because by 1.0 we will be targeting mobile. we may want this added to the current release, but it's redundant for dev

**Comment by achen5671** [comment]
> I wasn't involved with picking the wording of this message, so maybe it's exactly as intended, but should there be an additional sentence or sentence fragment like "for best experience use desktop Chrome"? Or changing it from saying "mobile not supported" to "not optimized for mobile, experience might have issues"? To me, there's a disconnect between the modal saying mobile isn't supported and then, on mobile Chrome, at least, the scene loading and then appearing to be fine (granted, I just tested this on the default and sky-station scenes, so heavier/more complex scenes it might be more obvious).

I can change the copy and merge in

**Pull request merged**
