### PR TITLE
V0.8 studio: asset panel render by height

### PR DESCRIPTION
**Pull request by achen5671**
## References
closes #_insert number here_

### CODE REVIEW

**Comment by aditya-mitra** [comment]
we should always base off from `dev` branch
since commits are cherry-picked into `int` branch

**Comment by achen5671** [comment]
> we should always base off from `dev` branch since commits are cherry-picked into `int` branch

I was told we should branch of int right now, cc: @DanielBelmes

**Comment by DanielBelmes** [comment]
Yup sorry I was hoping it would get to you through Rahul and Josh. @aditya-mitra all fixes for V0.8 will occur in int and be brought over to dev now. We found it's a more consistent release path than what we were doing earlier.

**Comment by achen5671** [comment]
@DanielBelmes @aditya-mitra after discussions, looks like we are going to move it so it branches off dev. Let me know if there are any objection

**Comment by achen5671** [comment]
closing infavor of https://github.com/ir-engine/ir-engine/pull/183

**Pull request closed without merging**
