### PR TITLE
Implement Camera Gizmo

### PR DESCRIPTION
**Pull request by SYBIOTE**
Implements a camera gizmo which allows for easy manipulation of the scene camera

### CODE REVIEW

**Comment by DanielBelmes** [comment]
Still not working when I have an object selected but otherwise looks really good.

**Comment by DanielBelmes** [comment]
still have to review code

**Comment by SYBIOTE** [comment]
> Still not working when I have an object selected but otherwise looks really good.

yeah the transform gizmo's input component, takes over the camera gizmo's i don't quite understand why that happens

**Comment by SYBIOTE** [comment]
> > Still not working when I have an object selected but otherwise looks really good.
> 
> yeah the transform gizmo's input component, takes over the camera gizmo's i don't quite understand why that happens

yup absolutely no idea what's happening, i understand that the presence of the transform gizmo is somehow messing with the input of the camera gizmo but i have no idea why
@DanielBelmes

**Comment by SamMazerIR** [comment]
pushed a fix for input heuristics. should be good now regardless of whether you're selecting an object

**Review by SamMazerIR — APPROVED** [review]

**Review by HexaField — CHANGES_REQUESTED** [review]
when i click the camera preview entity the scene is scaled up

**Comment by SYBIOTE** [comment]
> when i click the camera preview entity the scene is scaled up

i dont see the issue on my end

**Comment by SYBIOTE** [comment]
@HexaField , any update on this

**Comment by HexaField** [comment]
> @HexaField , any update on this

Try the sky station. It might have something to do with the scene preview camera being disabled. All you need to do to reproduce is open the sky station in the studio and select the scene preview camera entity.

**Comment by SYBIOTE** [comment]
seems like a separate issue? the zooming happens when you select the scene preview camera when its invisible, if you make the scene preview camera visible again, it will revert back to appropriate zoom level

**Comment by SYBIOTE** [comment]
the problem exists in dev as well, can we solve the bug separately from this PR?
@HexaField

**Comment by HexaField** [comment]
> the problem exists in dev as well, can we solve the bug separately from this PR?
> @HexaField 

Gotcha. Yes, no worries then.

**Review by HexaField — APPROVED** [review]

**Pull request merged**
