### PR TITLE
refactor files panel

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Summary

Old Folder Layout (in ui package `src/components/editor/panels/Files`)

```
.
 |-index.tsx
 |-index.stories.tsx
 |-browserGrid
 | |-index.tsx
 | |-DeleteFileModal.tsx
 | |-ImageConvertModal.tsx
 | |-RenameFileModal.tsx
 | |-FilePropertiesModal.tsx
 |-container
 | |-index.tsx
 | |-index.stories.tsx
 |-download
 | |-projectDownload.tsx
 |-icon
 | |-index.tsx
 |-upload
 | |-FileUploadProgress.tsx
```

New Folder Layout (in editor package `src/panels/files`)

```
.
 |-files
 | |-index.tsx                                         
 | |-toolbar.tsx                             (all the items on toolbar like view mode selection, breadcrumbs, etc.)
 | |-fileitem.tsx                             (grid and table view for each file)
 | |-modals
 | | |-DeleteFileModal.tsx
 | | |-ImageConvertModal.tsx
 | | |-RenameFileModal.tsx
 | | |-FilePropertiesModal.tsx
 | |-contextmenu.tsx                            (file item and panel context menu)
 | |-loaders.tsx                              (loading progress like generating thumbnails, project download, etc.)
 | |-helpers.tsx                              (new hooks including useCurrentFiles and useFileBrowserDrop)
 | |-fileicon.tsx
 | |-filebrowser.tsx                        (rendering all the files one by one into fileitem.tsx)
```

## References
closes #_insert number here_

### CODE REVIEW

**Comment by achen5671** [comment]
Screenshot 2024-08-27 at 10 20 05 PM

the arrows are not aligned

**Comment by achen5671** [comment]
Screenshot 2024-08-27 at 10 38 24 PM

the save changes and discard button doesnt work for file properties modal

**Comment by achen5671** [comment]
Screenshot 2024-08-27 at 10 47 10 PM

Is the upload button disabled for a reason?

**Comment by aditya-mitra** [comment]
> Screenshot 2024-08-27 at 10 47 10 PM
> Is the upload button disabled for a reason?

Yes, uploading is only enabled in public or assets folders

**Comment by aditya-mitra** [comment]
> Screenshot 2024-08-27 at 10 20 05 PM
> the arrows are not aligned

Yes, that is happening because of an incorrect folder design
Have informed Tarek for corrections
image

Edit: The folder icon has been updated correctly now

**Comment by aditya-mitra** [comment]
> Screenshot 2024-08-27 at 10 38 24 PM
> the save changes and discard button doesnt work for file properties modal

seems to be working fine on my end

https://github.com/user-attachments/assets/eac85d20-b923-4bed-847b-2adce5d34cc2

**Review by CITIZENDOT — CHANGES_REQUESTED** [review]
image
can we trim the names of the files, when it's too long? we can just show first few chars and extension. full name is shown in the tooltip anyway.

for example:
image

**Comment by CITIZENDOT** [comment]
also, can we have subtle hover colors for context menus?

**Comment by aditya-mitra** [comment]
> image can we trim the names of the files, when it's too long? we can just show first few chars and extension. full name is shown in the tooltip anyway.
> 
> for example: image

fixed 
image

**Comment by aditya-mitra** [comment]
> also, can we have subtle hover colors for context menus?

asked Tarek for this
i tried adding some opacity but it was making the button like bad on hover

**Review by CITIZENDOT — APPROVED** [review]
Looks great!

**Pull request merged**
